# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int64'), 3, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int64'), 9, numpy.ndarray)

In [7]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int64'), 18, numpy.ndarray)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
step_array = np.array(range(0, 100, 3))
step_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_ints = np.random.randint(0, 10, size=(7, 2))
random_array_ints

array([[1, 3],
       [8, 1],
       [9, 8],
       [9, 4],
       [1, 3],
       [6, 7],
       [2, 0]])

In [33]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_floats = np.random.random(size=(3, 5))
random_array_floats

array([[0.32533033, 0.38867729, 0.27134903, 0.82873751, 0.35675333],
       [0.28093451, 0.54269608, 0.14092422, 0.80219698, 0.07455064],
       [0.98688694, 0.77224477, 0.19871568, 0.00552212, 0.81546143]])

In [36]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_seed = np.random.randint(0, 10, size=(4, 6))
random_array_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(random_array)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [42]:
random_array

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6],
       [2, 9, 5, 6, 4, 7, 9]])

In [43]:
# Find the 0'th index of the latest array you created
random_array[0]

array([7, 9, 3, 7, 1, 4, 4])

In [44]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [59]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[7, 9],
       [5, 7]])

In [60]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))

In [61]:
random_array

array([[6, 0, 0, 8, 8],
       [3, 8, 2, 6, 5],
       [7, 8, 4, 0, 2]])

In [62]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
# Add the two arrays together
np.add(random_array, ones)

array([[7., 1., 1., 9., 9.],
       [4., 9., 3., 7., 6.],
       [8., 9., 5., 1., 3.]])

In [64]:
# Create another array of ones of shape (5, 3)
another_ones = np.ones((5, 3))
another_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
# Try add the array of ones and the other most recent array together
# np.add(random_array, another_ones)

reshaped_ones = another_ones.reshape((3, 5))
np.add(random_array, reshaped_ones)

array([[7., 1., 1., 9., 9.],
       [4., 9., 3., 7., 6.],
       [8., 9., 5., 1., 3.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [67]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))

In [68]:
# Subtract the new array of ones from the other most recent array
np.subtract(random_array, ones)

array([[ 5., -1., -1.,  7.,  7.],
       [ 2.,  7.,  1.,  5.,  4.],
       [ 6.,  7.,  3., -1.,  1.]])

In [69]:
# Multiply the ones array with the latest array
np.multiply(random_array, ones)

array([[6., 0., 0., 8., 8.],
       [3., 8., 2., 6., 5.],
       [7., 8., 4., 0., 2.]])

In [70]:
# Take the latest array to the power of 2 using '**'
random_array ** 2

array([[36,  0,  0, 64, 64],
       [ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4]])

In [71]:
# Do the same thing with np.square()
np.square(random_array)

array([[36,  0,  0, 64, 64],
       [ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4]])

In [72]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)

4.466666666666667

In [73]:
# Find the maximum of the latest array using np.max()
np.max(random_array)

8

In [74]:
# Find the minimum of the latest array using np.min()
np.min(random_array)

0

In [75]:
# Find the standard deviation of the latest array
np.std(random_array)

3.0081371127142607

In [76]:
# Find the variance of the latest array
np.var(random_array)

9.04888888888889

In [77]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = np.reshape(random_array, (3, 5, 1))
reshaped_array

array([[[6],
        [0],
        [0],
        [8],
        [8]],

       [[3],
        [8],
        [2],
        [6],
        [5]],

       [[7],
        [8],
        [4],
        [0],
        [2]]])

In [78]:
# Transpose the latest array
random_array.T

array([[6, 3, 7],
       [0, 8, 8],
       [0, 2, 4],
       [8, 6, 0],
       [8, 5, 2]])

What does the transpose do?

In [79]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_1 = np.random.randint(0, 10, size=(3, 3))
random_array_2 = np.random.randint(0, 10, size=(3, 2))

In [80]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_1, random_array_2)

array([[34, 88],
       [29, 70],
       [ 0, 36]])

In [81]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_1 = np.random.randint(0, 10, size=(4, 3))
random_array_2 = np.random.randint(0, 10, size=(4, 3))

In [82]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_1, random_array_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [83]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
transposed_random_array_2 = random_array_2.T
np.dot(random_array_1, transposed_random_array_2)

array([[28, 42, 49, 49],
       [13,  9,  7, 11],
       [65, 73, 72, 83],
       [18,  6,  0,  8]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [93]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_1 = np.random.randint(0, 10, size=(4, 3))
random_array_2 = np.random.randint(0, 10, size=(4, 3))

In [94]:
random_array_1

array([[8, 8, 1],
       [6, 9, 2],
       [6, 9, 8],
       [3, 0, 1]])

In [95]:
random_array_2

array([[0, 4, 4],
       [6, 8, 8],
       [2, 2, 2],
       [3, 7, 5]])

In [96]:
# Compare the two arrays with '>'
random_array_1 > random_array_2

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [97]:
# Compare the two arrays with '>='
random_array_1 >= random_array_2

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [98]:
# Find which elements of the first array are greater than 7
random_array_1 > 7

array([[ True,  True, False],
       [False,  True, False],
       [False,  True,  True],
       [False, False, False]])

In [99]:
# Which parts of each array are equal? (try using '==')
random_array_1 == random_array_2

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [ True, False, False]])

In [105]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array_1)
random_array_1

array([[1, 8, 8],
       [2, 6, 9],
       [6, 8, 9],
       [0, 1, 3]])

In [106]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [107]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_1)

5

In [108]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_1)

9

In [109]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(random_array_1, axis=0)

array([2, 0, 1])

In [110]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmin(random_array_1, axis=1)

array([0, 0, 0, 0])

In [127]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.20245753,  0.06089661,  0.6471627 ,  0.12609483, -1.89737698],
       [ 1.28054076, -0.61513368,  2.11131764,  0.68684851,  0.07097242],
       [ 0.43932714, -0.10849789, -0.48643277,  0.20759826,  0.88499047]])

In [128]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.